/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPage {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'posts' : Array<BlogPost>,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : Timestamp,
  'author' : string,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : string,
  'readTimeMinutes' : bigint,
}
export type DesignId = bigint;
export interface DesignResult {
  'id' : DesignId,
  'shareUrl' : [] | [string],
  'createdAt' : Timestamp,
  'selectedStyle' : string,
  'imageKey' : string,
}
export type DesignStyle = { 'Luxury' : null } |
  { 'Eclectic' : null } |
  { 'Minimalist' : null } |
  { 'Modern' : null };
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'afterImageUrl' : string,
  'beforeImageUrl' : string,
  'description' : string,
  'style' : DesignStyle,
  'relatedProductIds' : Array<bigint>,
  'designTips' : Array<string>,
  'roomType' : RoomType,
}
export type RoomType = { 'Kitchen' : null } |
  { 'Studio' : null } |
  { 'LivingRoom' : null } |
  { 'Bedroom' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getFeaturedBlogPosts' : ActorMethod<[bigint], Array<BlogPost>>,
  'getGalleryItem' : ActorMethod<[bigint], [] | [GalleryItem]>,
  'getRelatedBlogPosts' : ActorMethod<
    [string, bigint, bigint],
    Array<BlogPost>
  >,
  'listBlogPostsByCategory' : ActorMethod<[string, bigint, bigint], BlogPage>,
  'listGalleryItems' : ActorMethod<
    [[] | [RoomType], [] | [DesignStyle]],
    Array<GalleryItem>
  >,
  'listMyDesigns' : ActorMethod<[], Array<DesignResult>>,
  'saveDesign' : ActorMethod<[string, string], DesignResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];