/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Timestamp,
  'author' : IDL.Text,
  'featuredImageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'readTimeMinutes' : IDL.Nat,
});
export const DesignStyle = IDL.Variant({
  'Luxury' : IDL.Null,
  'Eclectic' : IDL.Null,
  'Minimalist' : IDL.Null,
  'Modern' : IDL.Null,
});
export const RoomType = IDL.Variant({
  'Kitchen' : IDL.Null,
  'Studio' : IDL.Null,
  'LivingRoom' : IDL.Null,
  'Bedroom' : IDL.Null,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'afterImageUrl' : IDL.Text,
  'beforeImageUrl' : IDL.Text,
  'description' : IDL.Text,
  'style' : DesignStyle,
  'relatedProductIds' : IDL.Vec(IDL.Nat),
  'designTips' : IDL.Vec(IDL.Text),
  'roomType' : RoomType,
});
export const BlogPage = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'posts' : IDL.Vec(BlogPost),
});
export const DesignId = IDL.Nat;
export const DesignResult = IDL.Record({
  'id' : DesignId,
  'shareUrl' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'selectedStyle' : IDL.Text,
  'imageKey' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getFeaturedBlogPosts' : IDL.Func([IDL.Nat], [IDL.Vec(BlogPost)], ['query']),
  'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
  'getRelatedBlogPosts' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'listBlogPostsByCategory' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [BlogPage],
      ['query'],
    ),
  'listGalleryItems' : IDL.Func(
      [IDL.Opt(RoomType), IDL.Opt(DesignStyle)],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'listMyDesigns' : IDL.Func([], [IDL.Vec(DesignResult)], ['query']),
  'saveDesign' : IDL.Func([IDL.Text, IDL.Text], [DesignResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Timestamp,
    'author' : IDL.Text,
    'featuredImageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'readTimeMinutes' : IDL.Nat,
  });
  const DesignStyle = IDL.Variant({
    'Luxury' : IDL.Null,
    'Eclectic' : IDL.Null,
    'Minimalist' : IDL.Null,
    'Modern' : IDL.Null,
  });
  const RoomType = IDL.Variant({
    'Kitchen' : IDL.Null,
    'Studio' : IDL.Null,
    'LivingRoom' : IDL.Null,
    'Bedroom' : IDL.Null,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'afterImageUrl' : IDL.Text,
    'beforeImageUrl' : IDL.Text,
    'description' : IDL.Text,
    'style' : DesignStyle,
    'relatedProductIds' : IDL.Vec(IDL.Nat),
    'designTips' : IDL.Vec(IDL.Text),
    'roomType' : RoomType,
  });
  const BlogPage = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'posts' : IDL.Vec(BlogPost),
  });
  const DesignId = IDL.Nat;
  const DesignResult = IDL.Record({
    'id' : DesignId,
    'shareUrl' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'selectedStyle' : IDL.Text,
    'imageKey' : IDL.Text,
  });
  
  return IDL.Service({
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getFeaturedBlogPosts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
    'getRelatedBlogPosts' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'listBlogPostsByCategory' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [BlogPage],
        ['query'],
      ),
    'listGalleryItems' : IDL.Func(
        [IDL.Opt(RoomType), IDL.Opt(DesignStyle)],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'listMyDesigns' : IDL.Func([], [IDL.Vec(DesignResult)], ['query']),
    'saveDesign' : IDL.Func([IDL.Text, IDL.Text], [DesignResult], []),
  });
};

export const init = ({ IDL }) => { return []; };