/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: bigint;
    title: string;
    body: string;
    slug: string;
    tags: Array<string>;
    publishedAt: Timestamp;
    author: string;
    featuredImageUrl: string;
    excerpt: string;
    category: string;
    readTimeMinutes: bigint;
}
export type Timestamp = bigint;
export interface BlogPage {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    posts: Array<BlogPost>;
}
export interface GalleryItem {
    id: bigint;
    title: string;
    afterImageUrl: string;
    beforeImageUrl: string;
    description: string;
    style: DesignStyle;
    relatedProductIds: Array<bigint>;
    designTips: Array<string>;
    roomType: RoomType;
}
export interface DesignResult {
    id: DesignId;
    shareUrl?: string;
    createdAt: Timestamp;
    selectedStyle: string;
    imageKey: string;
}
export type DesignId = bigint;
export enum DesignStyle {
    Luxury = "Luxury",
    Eclectic = "Eclectic",
    Minimalist = "Minimalist",
    Modern = "Modern"
}
export enum RoomType {
    Kitchen = "Kitchen",
    Studio = "Studio",
    LivingRoom = "LivingRoom",
    Bedroom = "Bedroom"
}
export interface backendInterface {
    getBlogPostBySlug(slug: string): Promise<BlogPost | null>;
    getFeaturedBlogPosts(limit: bigint): Promise<Array<BlogPost>>;
    getGalleryItem(id: bigint): Promise<GalleryItem | null>;
    getRelatedBlogPosts(category: string, excludeId: bigint, limit: bigint): Promise<Array<BlogPost>>;
    listBlogPostsByCategory(category: string, page: bigint, pageSize: bigint): Promise<BlogPage>;
    listGalleryItems(roomType: RoomType | null, style: DesignStyle | null): Promise<Array<GalleryItem>>;
    listMyDesigns(): Promise<Array<DesignResult>>;
    saveDesign(imageKey: string, selectedStyle: string): Promise<DesignResult>;
}
import type { BlogPost as _BlogPost, DesignId as _DesignId, DesignResult as _DesignResult, DesignStyle as _DesignStyle, GalleryItem as _GalleryItem, RoomType as _RoomType, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getBlogPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedBlogPosts(arg0: bigint): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedBlogPosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedBlogPosts(arg0);
            return result;
        }
    }
    async getGalleryItem(arg0: bigint): Promise<GalleryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItem(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItem(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelatedBlogPosts(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelatedBlogPosts(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelatedBlogPosts(arg0, arg1, arg2);
            return result;
        }
    }
    async listBlogPostsByCategory(arg0: string, arg1: bigint, arg2: bigint): Promise<BlogPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPostsByCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPostsByCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async listGalleryItems(arg0: RoomType | null, arg1: DesignStyle | null): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryItems(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryItems(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyDesigns(): Promise<Array<DesignResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyDesigns();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyDesigns();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDesign(arg0: string, arg1: string): Promise<DesignResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDesign(arg0, arg1);
                return from_candid_DesignResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDesign(arg0, arg1);
            return from_candid_DesignResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DesignResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignResult): DesignResult {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DesignStyle_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignStyle): DesignStyle {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_GalleryItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): GalleryItem {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryItem]): GalleryItem | null {
    return value.length === 0 ? null : from_candid_GalleryItem_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DesignId;
    shareUrl: [] | [string];
    createdAt: _Timestamp;
    selectedStyle: string;
    imageKey: string;
}): {
    id: DesignId;
    shareUrl?: string;
    createdAt: Timestamp;
    selectedStyle: string;
    imageKey: string;
} {
    return {
        id: value.id,
        shareUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.shareUrl)),
        createdAt: value.createdAt,
        selectedStyle: value.selectedStyle,
        imageKey: value.imageKey
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    afterImageUrl: string;
    beforeImageUrl: string;
    description: string;
    style: _DesignStyle;
    relatedProductIds: Array<bigint>;
    designTips: Array<string>;
    roomType: _RoomType;
}): {
    id: bigint;
    title: string;
    afterImageUrl: string;
    beforeImageUrl: string;
    description: string;
    style: DesignStyle;
    relatedProductIds: Array<bigint>;
    designTips: Array<string>;
    roomType: RoomType;
} {
    return {
        id: value.id,
        title: value.title,
        afterImageUrl: value.afterImageUrl,
        beforeImageUrl: value.beforeImageUrl,
        description: value.description,
        style: from_candid_DesignStyle_n5(_uploadFile, _downloadFile, value.style),
        relatedProductIds: value.relatedProductIds,
        designTips: value.designTips,
        roomType: from_candid_RoomType_n7(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Luxury: null;
} | {
    Eclectic: null;
} | {
    Minimalist: null;
} | {
    Modern: null;
}): DesignStyle {
    return "Luxury" in value ? DesignStyle.Luxury : "Eclectic" in value ? DesignStyle.Eclectic : "Minimalist" in value ? DesignStyle.Minimalist : "Modern" in value ? DesignStyle.Modern : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Kitchen: null;
} | {
    Studio: null;
} | {
    LivingRoom: null;
} | {
    Bedroom: null;
}): RoomType {
    return "Kitchen" in value ? RoomType.Kitchen : "Studio" in value ? RoomType.Studio : "LivingRoom" in value ? RoomType.LivingRoom : "Bedroom" in value ? RoomType.Bedroom : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Array<GalleryItem> {
    return value.map((x)=>from_candid_GalleryItem_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DesignResult>): Array<DesignResult> {
    return value.map((x)=>from_candid_DesignResult_n17(_uploadFile, _downloadFile, x));
}
function to_candid_DesignStyle_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignStyle): _DesignStyle {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignStyle | null): [] | [_DesignStyle] {
    return value === null ? candid_none() : candid_some(to_candid_DesignStyle_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType | null): [] | [_RoomType] {
    return value === null ? candid_none() : candid_some(to_candid_RoomType_n10(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    Kitchen: null;
} | {
    Studio: null;
} | {
    LivingRoom: null;
} | {
    Bedroom: null;
} {
    return value == RoomType.Kitchen ? {
        Kitchen: null
    } : value == RoomType.Studio ? {
        Studio: null
    } : value == RoomType.LivingRoom ? {
        LivingRoom: null
    } : value == RoomType.Bedroom ? {
        Bedroom: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignStyle): {
    Luxury: null;
} | {
    Eclectic: null;
} | {
    Minimalist: null;
} | {
    Modern: null;
} {
    return value == DesignStyle.Luxury ? {
        Luxury: null
    } : value == DesignStyle.Eclectic ? {
        Eclectic: null
    } : value == DesignStyle.Minimalist ? {
        Minimalist: null
    } : value == DesignStyle.Modern ? {
        Modern: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
